### ISSUE TITLE
Setup GitHub Actions to run tests in PRs

### ISSUE THREAD

**Issue by cesargdm** [code4mexico/transporteCDMX#10]

**Comment by code-for-mexico** [comment]
@cesargdm I only have experience configuring that in a CI with e2e tests. Never used GitHub actions. Could you send me some good reference so I can configure it?
I had in mind to configure a CI but if we can solve it with GitHub actions might be better

**Comment by cesargdm** [comment]
I’m preparing a PR for that, it would be just to lint code and run tests at PRs

**Comment by cesargdm** [comment]
@code-for-mexico https://github.com/cesargdm/transporteCDMX/pull/2

**Comment by code-for-mexico** [comment]
I like it. Thanks again for this.
